apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: pip-e2e-test-ccye
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: pip-e2e-test-ccye
    app.kubernetes.io/part-of: test-app-887
  name: pip-e2e-test-ccye
spec:
  replicas: 0
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: pip-e2e-test
      app.kubernetes.io/instance: pip-e2e-test-ccye
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: pip-e2e-test
        app.kubernetes.io/instance: pip-e2e-test-ccye
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/build-templates-e2e/test-app-887/pip-e2e-test-ccye@sha256:a0661ca7efee77ab8bbd0868f6362c840793f7604b18d5e7fc580ba696eec958
        name: pip-e2e-test
        ports:
        - containerPort: 8081
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
