apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: retrodep-flnv
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: retrodep-flnv
    app.kubernetes.io/part-of: test-app-887
  name: retrodep-flnv
spec:
  replicas: 0
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: my-retrodep
      app.kubernetes.io/instance: retrodep-flnv
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: my-retrodep
        app.kubernetes.io/instance: retrodep-flnv
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/build-templates-e2e/test-app-887/retrodep-flnv@sha256:002173663666b100c3e5475f524bba910425465f04a7628d14da7dad433b58f3
        name: my-retrodep
        ports:
        - containerPort: 8081
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
