apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: fbc-sample-repo-lslc
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: fbc-sample-repo-lslc
    app.kubernetes.io/part-of: test-app-887
  name: fbc-sample-repo-lslc
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: fbc
      app.kubernetes.io/instance: fbc-sample-repo-lslc
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: fbc
        app.kubernetes.io/instance: fbc-sample-repo-lslc
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/build-templates-e2e/test-app-887/fbc-sample-repo-lslc@sha256:fa8a57d153b6e06a046dd51f3c71cdad6f84f74fdd8ce90f72244c2e98c60450
        name: fbc
        ports:
        - containerPort: 50051
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
          requests:
            cpu: 100m
            memory: 512Mi
status: {}
