apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: e2e-tests-use-latest-parent-image-idxc
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: e2e-tests-use-latest-parent-image-idxc
    app.kubernetes.io/part-of: test-app-887
  name: e2e-tests-use-latest-parent-image-idxc
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/instance: e2e-tests-use-latest-parent-image-idxc
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: e2e-tests-use-latest-parent-image-idxc
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/build-templates-e2e/test-app-887/e2e-tests-use-latest-parent-image-idxc@sha256:a8f97da95363457957265acd158fab16b265ba595f127a5f95dd9188c61241f9
        imagePullPolicy: Always
        name: container-image
        ports:
        - containerPort: 8081
        resources: {}
status: {}
