apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: nodejs-no-dockerfile-f15i
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: nodejs-no-dockerfile-f15i
    app.kubernetes.io/part-of: test-app-887
  name: nodejs-no-dockerfile-f15i
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: nodejs-no-dockerfile-f15i
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: nodejs-no-dockerfile-f15i
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/build-templates-e2e/test-app-887/nodejs-no-dockerfile-f15i@sha256:4efbbffd84aeb681c98a136f26ee1166ab8f21a8a8e7be0db710dffe2ae12cd7
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        - containerPort: 8080
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
